package pp.weiba.service.download.client.model;

import com.alibaba.fastjson.annotation.JSONField;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;

/**
 * @author xiaoweiba1028@gmail.com
 * @description 全局配置信息
 * @date 2023/5/30 23:07
 */
@NoArgsConstructor
@Accessors(chain = true)
@Data
@SuperBuilder
public class Aria2GlobalOption {

    @JSONField(name = "allow-overwrite")
    private String allowoverwrite;
    @JSONField(name = "allow-piece-length-change")
    private String allowpiecelengthchange;
    @JSONField(name = "always-resume")
    private String alwaysresume;
    @JSONField(name = "async-dns")
    private String asyncdns;
    @JSONField(name = "auto-file-renaming")
    private String autofilerenaming;
    @JSONField(name = "auto-save-interval")
    private String autosaveinterval;
    @JSONField(name = "bt-detach-seed-only")
    private String btdetachseedonly;
    @JSONField(name = "bt-enable-hook-after-hash-check")
    private String btenablehookafterhashcheck;
    @JSONField(name = "bt-enable-lpd")
    private String btenablelpd;
    @JSONField(name = "bt-force-encryption")
    private String btforceencryption;
    @JSONField(name = "bt-hash-check-seed")
    private String bthashcheckseed;
    @JSONField(name = "bt-load-saved-metadata")
    private String btloadsavedmetadata;
    @JSONField(name = "bt-max-open-files")
    private String btmaxopenfiles;
    @JSONField(name = "bt-max-peers")
    private String btmaxpeers;
    @JSONField(name = "bt-metadata-only")
    private String btmetadataonly;
    @JSONField(name = "bt-min-crypto-level")
    private String btmincryptolevel;
    @JSONField(name = "bt-prioritize-piece")
    private String btprioritizepiece;
    @JSONField(name = "bt-remove-unselected-file")
    private String btremoveunselectedfile;
    @JSONField(name = "bt-request-peer-speed-limit")
    private String btrequestpeerspeedlimit;
    @JSONField(name = "bt-require-crypto")
    private String btrequirecrypto;
    @JSONField(name = "bt-save-metadata")
    private String btsavemetadata;
    @JSONField(name = "bt-seed-unverified")
    private String btseedunverified;
    @JSONField(name = "bt-stop-timeout")
    private String btstoptimeout;
    @JSONField(name = "bt-tracker")
    private String bttracker;
    @JSONField(name = "bt-tracker-connect-timeout")
    private String bttrackerconnecttimeout;
    @JSONField(name = "bt-tracker-interval")
    private String bttrackerinterval;
    @JSONField(name = "bt-tracker-timeout")
    private String bttrackertimeout;
    @JSONField(name = "ca-certificate")
    private String cacertificate;
    @JSONField(name = "check-certificate")
    private String checkcertificate;
    @JSONField(name = "check-integrity")
    private String checkintegrity;
    @JSONField(name = "conditional-get")
    private String conditionalget;
    @JSONField(name = "conf-path")
    private String confpath;
    @JSONField(name = "connect-timeout")
    private String connecttimeout;
    @JSONField(name = "console-log-level")
    private String consoleloglevel;
    @JSONField(name = "content-disposition-default-utf8")
    private String contentdispositiondefaultutf8;
    @JSONField(name = "continue")
    private String continueX;
    private String daemon;
    @JSONField(name = "deferred-input")
    private String deferredinput;
    @JSONField(name = "dht-entry-point")
    private String dhtentrypoint;
    @JSONField(name = "dht-entry-point6")
    private String dhtentrypoint6;
    @JSONField(name = "dht-file-path")
    private String dhtfilepath;
    @JSONField(name = "dht-file-path6")
    private String dhtfilepath6;
    @JSONField(name = "dht-listen-port")
    private String dhtlistenport;
    @JSONField(name = "dht-message-timeout")
    private String dhtmessagetimeout;
    private String dir;
    @JSONField(name = "disable-ipv6")
    private String disableipv6;
    @JSONField(name = "disk-cache")
    private String diskcache;
    @JSONField(name = "download-result")
    private String downloadresult;
    @JSONField(name = "dry-run")
    private String dryrun;
    private String dscp;
    @JSONField(name = "enable-color")
    private String enablecolor;
    @JSONField(name = "enable-dht")
    private String enabledht;
    @JSONField(name = "enable-dht6")
    private String enabledht6;
    @JSONField(name = "enable-http-keep-alive")
    private String enablehttpkeepalive;
    @JSONField(name = "enable-http-pipelining")
    private String enablehttppipelining;
    @JSONField(name = "enable-mmap")
    private String enablemmap;
    @JSONField(name = "enable-peer-exchange")
    private String enablepeerexchange;
    @JSONField(name = "enable-rpc")
    private String enablerpc;
    @JSONField(name = "event-poll")
    private String eventpoll;
    @JSONField(name = "file-allocation")
    private String fileallocation;
    @JSONField(name = "follow-metalink")
    private String followmetalink;
    @JSONField(name = "follow-torrent")
    private String followtorrent;
    @JSONField(name = "force-save")
    private String forcesave;
    @JSONField(name = "ftp-pasv")
    private String ftppasv;
    @JSONField(name = "ftp-reuse-connection")
    private String ftpreuseconnection;
    @JSONField(name = "ftp-type")
    private String ftptype;
    @JSONField(name = "hash-check-only")
    private String hashcheckonly;
    private String help;
    @JSONField(name = "http-accept-gzip")
    private String httpacceptgzip;
    @JSONField(name = "http-auth-challenge")
    private String httpauthchallenge;
    @JSONField(name = "http-no-cache")
    private String httpnocache;
    @JSONField(name = "http-want-digest")
    private String httpwantdigest;
    @JSONField(name = "human-readable")
    private String humanreadable;
    @JSONField(name = "keep-unfinished-download-result")
    private String keepunfinisheddownloadresult;
    @JSONField(name = "listen-port")
    private String listenport;
    @JSONField(name = "log-level")
    private String loglevel;
    @JSONField(name = "lowest-speed-limit")
    private String lowestspeedlimit;
    @JSONField(name = "max-concurrent-downloads")
    private String maxconcurrentdownloads;
    @JSONField(name = "max-connection-per-server")
    private String maxconnectionperserver;
    @JSONField(name = "max-download-limit")
    private String maxdownloadlimit;
    @JSONField(name = "max-download-result")
    private String maxdownloadresult;
    @JSONField(name = "max-file-not-found")
    private String maxfilenotfound;
    @JSONField(name = "max-mmap-limit")
    private String maxmmaplimit;
    @JSONField(name = "max-overall-download-limit")
    private String maxoveralldownloadlimit;
    @JSONField(name = "max-overall-upload-limit")
    private String maxoveralluploadlimit;
    @JSONField(name = "max-resume-failure-tries")
    private String maxresumefailuretries;
    @JSONField(name = "max-tries")
    private String maxtries;
    @JSONField(name = "max-upload-limit")
    private String maxuploadlimit;
    @JSONField(name = "metalink-enable-unique-protocol")
    private String metalinkenableuniqueprotocol;
    @JSONField(name = "metalink-preferred-protocol")
    private String metalinkpreferredprotocol;
    @JSONField(name = "min-split-size")
    private String minsplitsize;
    @JSONField(name = "min-tls-version")
    private String mintlsversion;
    @JSONField(name = "netrc-path")
    private String netrcpath;
    @JSONField(name = "no-conf")
    private String noconf;
    @JSONField(name = "no-file-allocation-limit")
    private String nofileallocationlimit;
    @JSONField(name = "no-netrc")
    private String nonetrc;
    @JSONField(name = "on-download-complete")
    private String ondownloadcomplete;
    @JSONField(name = "on-download-stop")
    private String ondownloadstop;
    @JSONField(name = "optimize-concurrent-downloads")
    private String optimizeconcurrentdownloads;
    @JSONField(name = "parameterized-uri")
    private String parameterizeduri;
    @JSONField(name = "pause-metadata")
    private String pausemetadata;
    @JSONField(name = "peer-agent")
    private String peeragent;
    @JSONField(name = "peer-id-prefix")
    private String peeridprefix;
    @JSONField(name = "piece-length")
    private String piecelength;
    @JSONField(name = "proxy-method")
    private String proxymethod;
    private String quiet;
    @JSONField(name = "realtime-chunk-checksum")
    private String realtimechunkchecksum;
    @JSONField(name = "remote-time")
    private String remotetime;
    @JSONField(name = "remove-control-file")
    private String removecontrolfile;
    @JSONField(name = "retry-on-400")
    private String retryon400;
    @JSONField(name = "retry-on-403")
    private String retryon403;
    @JSONField(name = "retry-on-406")
    private String retryon406;
    @JSONField(name = "retry-on-unknown")
    private String retryonunknown;
    @JSONField(name = "retry-wait")
    private String retrywait;
    @JSONField(name = "reuse-uri")
    private String reuseuri;
    @JSONField(name = "rlimit-nofile")
    private String rlimitnofile;
    @JSONField(name = "rpc-allow-origin-all")
    private String rpcalloworiginall;
    @JSONField(name = "rpc-listen-all")
    private String rpclistenall;
    @JSONField(name = "rpc-listen-port")
    private String rpclistenport;
    @JSONField(name = "rpc-max-request-size")
    private String rpcmaxrequestsize;
    @JSONField(name = "rpc-save-upload-metadata")
    private String rpcsaveuploadmetadata;
    @JSONField(name = "rpc-secure")
    private String rpcsecure;
    @JSONField(name = "save-not-found")
    private String savenotfound;
    @JSONField(name = "save-session")
    private String savesession;
    @JSONField(name = "save-session-interval")
    private String savesessioninterval;
    @JSONField(name = "seed-ratio")
    private String seedratio;
    @JSONField(name = "seed-time")
    private String seedtime;
    @JSONField(name = "server-stat-timeout")
    private String serverstattimeout;
    @JSONField(name = "show-console-readout")
    private String showconsolereadout;
    @JSONField(name = "show-files")
    private String showfiles;
    @JSONField(name = "socket-recv-buffer-size")
    private String socketrecvbuffersize;
    private String split;
    private String stderr;
    private String stop;
    @JSONField(name = "stream-piece-selector")
    private String streampieceselector;
    @JSONField(name = "summary-interval")
    private String summaryinterval;
    private String timeout;
    @JSONField(name = "truncate-console-readout")
    private String truncateconsolereadout;
    @JSONField(name = "uri-selector")
    private String uriselector;
    @JSONField(name = "use-head")
    private String usehead;
    @JSONField(name = "user-agent")
    private String useragent;

}
